### ISSUE TITLE
Alvaro's comment at the mike (IETF 115)? 

### ISSUE THREAD

**Issue by ksriram25** [jhaas-pfrc/draft-ietf-idr-deprecate-as-set-confed-set#4]
Alvaro's comment at the mike (IETF 115):
https://www.youtube.com/watch?v=NtbRk3SiU0E&t=1970s  
What wording if any do we want to add?

**Comment by jhaas-pfrc** [comment]
We should not use the word obsolete at any place in the document.
We can use the word deprecate, but do so in the sense of sending routes that contain as-sets.  That is, you shouldn't send them.
We can use the word deprecate in the receive sense because if we get routes with them, we're intending to treat-as-withdraw.

We need to review the full output to see if we accomplish those goals.
Alvaro is also effectively suggesting we should clearly state the three things listed above in a concise way early in the document, perhaps abstract as well, so it's clear what we're doing.

I'd suggest we look at the full set of text again once we integrate your edits in your child branch.
